services:
  projects-showcase:
    build:
      context: .
      dockerfile: Containerfile
      args:
        BASE_PATH: /projects-showcase/
    image: localhost/projects-showcase:latest
    container_name: projects-showcase
    ports:
      - "8082:80"
    restart: always
